### ISSUE TITLE
Automatic renewal of SSL certificate

### ISSUE THREAD

**Issue by josvandervelde** [openml/openml.org#305]

**Comment by josvandervelde** [comment]
Done, see https://github.com/openml/openml-internal-infra-wiki/blob/main/pages/webserver.md

**Comment by adubowski** [comment]
@josvandervelde I am not sure it worked, as I am getting an SSL: CERTIFICATE_VERIFY_FAILED error. Could you check if the server works correctly?

**Comment by josvandervelde** [comment]
Hi @adubowski , thanks for the response! 
Could you share a reproduction for this issue? What url where you accessing, and how? Thanks!

**Comment by adubowski** [comment]
Hi Jos, it seems that it was a problem on my side. In particular, the issue came from the lack of `certifi` package and relevant certificates on a new OSX Python installation. Steps in this thread helped me solve the issue: [https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)

**Comment by josvandervelde** [comment]
Great, thank you for the extra details.
